server:
  port: 3000

spring:
  application:
    name: yun-luo-blog
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./blog.db?date_string_format=yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

yun-luo-blog:
  username: admin
  password: 123456
